import numerics


if __name__ == '__main__':

    print(numerics.left_pad_zeros_for_a_number(23, 5))

    print(numerics.make_integer_an_adjective(1))
    print(numerics.make_integer_an_adjective(10))
    print(numerics.make_integer_an_adjective(11))
    print(numerics.make_integer_an_adjective(21))
    print(numerics.make_integer_an_adjective(24))
    print(numerics.make_integer_an_adjective(222))
    print(numerics.make_integer_an_adjective(2223))
    print(numerics.make_integer_an_adjective(222229))
    print(numerics.make_integer_an_adjective(222222))
    print(numerics.make_integer_an_adjective(222220))
    print(numerics.make_integer_an_adjective(300))
    print(numerics.make_integer_an_adjective(301))
    print(numerics.make_integer_an_adjective(302))
    print(numerics.make_integer_an_adjective(303))
    print(numerics.make_integer_an_adjective(304))
    print(numerics.make_integer_an_adjective(305))
    print(numerics.make_integer_an_adjective(306))
    print(numerics.make_integer_an_adjective(307))
    print(numerics.make_integer_an_adjective(308))
    print(numerics.make_integer_an_adjective(309))
    print(numerics.make_integer_an_adjective(310))
    print(numerics.make_integer_an_adjective(311))
    print(numerics.make_integer_an_adjective(312))
    print(numerics.make_integer_an_adjective(313))
    print(numerics.make_integer_an_adjective(314))
    print(numerics.make_integer_an_adjective(315))
    print(numerics.make_integer_an_adjective(316))
    print(numerics.make_integer_an_adjective(317))
    print(numerics.make_integer_an_adjective(318))
    print(numerics.make_integer_an_adjective(319))
    print(numerics.make_integer_an_adjective(320))
    print(numerics.make_integer_an_adjective(321))
    print(numerics.make_integer_an_adjective(322))
    print(numerics.make_integer_an_adjective(323))
    print(numerics.make_integer_an_adjective(324))
